# Generated by Django 4.1 on 2023-03-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('collegename', models.CharField(max_length=60)),
                ('roll', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=30)),
                ('aadhar', models.PositiveIntegerField()),
                ('previous_pass', models.BooleanField()),
                ('pass_number', models.PositiveIntegerField()),
            ],
        ),
    ]
