# Generated by Django 4.1 on 2023-03-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('e_sign', models.ImageField(default='', upload_to='home/e_sign')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('payment', models.BooleanField()),
                ('pass_file', models.ImageField(default='', upload_to='home/pass')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='home.college')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='home.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('roll', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=30)),
                ('aadhar_photo', models.ImageField(default='', upload_to='home/aadhar_photo')),
                ('aadhar_number', models.PositiveIntegerField()),
                ('previous_pass', models.BooleanField()),
                ('pass_number', models.CharField(max_length=30)),
                ('verify_college', models.BooleanField()),
                ('photo', models.ImageField(default='', upload_to='home/profile_photo')),
                ('current_pass', models.BooleanField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('verify_manager', models.BooleanField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='home.college')),
                ('route_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_from_created', to='home.route')),
                ('route_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_to_created', to='home.route')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='pass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='home.student'),
        ),
    ]
