# Generated by Django 4.1 on 2023-04-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_college_manager_pass_route_student_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='verify_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='verify_manager',
            field=models.BooleanField(default=False),
        ),
    ]
