# Generated by Django 4.1 on 2023-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_current_pass_alter_student_pass_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='price',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='valid_from',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='valid_to',
            field=models.DateField(default=''),
        ),
    ]
