# Generated by Django 4.1 on 2023-04-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_student_price_alter_student_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
