# Generated by Django 4.1 on 2023-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_student_valid_from_alter_student_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
