# Generated by Django 4.1 on 2023-04-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_student_route_from_alter_student_route_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
